development:
  adapter: mysql2
  database: t4newdev
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  #socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql2
  database: t4newtest
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: t4newdev
  username: root
  password:
  host: localhost
  pool: 10
  timeout: 5000
cucumber:
  <<: *test

